# Configuration de développement pour Jekyll
# Utilisez ce fichier avec: bundle exec jekyll serve --config _config.yml,_config.dev.yml

# Paramètres de développement
port: 4001
host: 0.0.0.0
livereload: true
incremental: true
watch: true

# Désactiver certaines optimisations en développement
minify: false
compress: false

# Configuration Sass pour supprimer les warnings de dépréciation
sass:
  quiet_deps: true

# Désactiver jekyll-compress-images en développement pour éviter les boucles de hotreload
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-minifier
