# Configuration de développement pour Jekyll
# Utilisez ce fichier avec: bundle exec jekyll serve --config _config.yml,_config.dev.yml

# Paramètres de développement
port: 4001
host: 0.0.0.0
livereload: true
incremental: true
watch: true

# Désactiver certaines optimisations en développement
minify: false
compress: false
